#项目启动端口
server:
  port: 8081
#数据源配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/city?serverTimezone=UTC&useSSL=false
    password: 1234
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver

#配置mybatis
mybatis:
  mapper-locations: classpath:com/city/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
#sql语句日志打印
logging:
  level:
    com:
      mashibing:
        mapper: debug